artist = Artist.create!(name: 'Bon Jovi')
artist.songs.create!(title: 'All The Small Things', length: 220, play_count: 10)
artist.songs.create!(title: 'Make Damn Sure', length: 230, play_count: 11)
artist.songs.create!(title: 'Seventy Time Seven', length: 240, play_count: 12)
artist.songs.create!(title: 'She', length: 260, play_count: 13)
artist.songs.create!(title: 'Helena', length: 250, play_count: 14)
artist.songs.create!(title: 'First Date', length: 270, play_count: 15)
artist.songs.create!(title: "Feelin' This", length: 280, play_count: 16)
artist.songs.create!(title: 'Cute Without the E', length: 290, play_count: 17)
artist.songs.create!(title: 'Everlong', length: 300, play_count: 18)
artist.songs.create!(title: 'Play Crack The Sky', length: 310, play_count: 19)
